### ISSUE TITLE
type incorrect，when some resource can not be deleted

### ISSUE THREAD

**Issue by 13567436138** [kubevela/kubevela#4958] opened 2022-10-30 06:18 UTC
**Describe the bug**

type incorrect，when some resource can not be deleted
**To Reproduce**

apply the yaml in order as flowing:
before you should install nfs in some machine:
```
132:
yum -y install rpcbind nfs-utils
vim /etc/exports
mkdir /nfs_data
/nfs_data 192.168.0.0/16(rw,no_root_squash,no_all_squash,sync)
/usr/sbin/exportfs -rv
systemctl start rpcbind 
systemctl start nfs-server
131:
/usr/bin/mount  -t nfs 192.168.229.132:/nfs_data /mnt

```

```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: task
spec:
  components:
    - name: job
      type: task
      properties:
        image: busybox
        cmd: ["echo","Hello World"]
        volumes:
        - name: test
          mountPath: /var/test
          type: pvc
          claimName: test-claim
    - name: nfs
      type: k8s-objects
      properties:
        objects:
          - apiVersion: v1
            kind: ServiceAccount
            metadata:
              name: nfs-provisioner
          - kind: ClusterRole
            apiVersion: rbac.authorization.k8s.io/v1
            metadata:
               name: nfs-provisioner-runner
            rules:
               -  apiGroups: [""]
                  resources: ["persistentvolumes"]
                  verbs: ["get", "list", "watch", "create", "delete"]
               -  apiGroups: [""]
                  resources: ["persistentvolumeclaims"]
                  verbs: ["get", "list", "watch", "update"]
               -  apiGroups: ["storage.k8s.io"]
                  resources: ["storageclasses"]
                  verbs: ["get", "list", "watch"]
               -  apiGroups: [""]
                  resources: ["events"]
                  verbs: ["watch", "create", "update", "patch"]
               -  apiGroups: [""]
                  resources: ["services", "endpoints"]
                  verbs: ["get", "list", "watch", "create", "update", "patch"]
               -  apiGroups: ["extensions"]
                  resources: ["podsecuritypolicies"]
                  resourceNames: ["nfs-provisioner"]
                  verbs: ["use"]
          - kind: ClusterRoleBinding
            apiVersion: rbac.authorization.k8s.io/v1
            metadata:
              name: run-nfs-provisioner
            subjects:
              - kind: ServiceAccount
                name: nfs-provisioner
                namespace: prod
            roleRef:
              kind: ClusterRole
              name: nfs-provisioner-runner
              apiGroup: rbac.authorization.k8s.io
          - kind: Deployment
            apiVersion: apps/v1
            metadata:
               name: nfs-client-provisioner
            spec:
               selector:
                 matchLabels:
                   app: nfs-client-provisioner
               replicas: 1
               strategy:
                 type: Recreate
               template:
                  metadata:
                    labels:
                      app: nfs-client-provisioner
                  spec:
                    serviceAccount: nfs-provisioner
                    containers:
                        -  name: nfs-client-provisioner
                           image: quay.io/external_storage/nfs-client-provisioner:latest
                           volumeMounts:
                             -  name: nfs-client-root
                                mountPath:  /persistentvolumes
                           env:
                             -  name: PROVISIONER_NAME
                                value: fuseim.pri/ifs
                             -  name: NFS_SERVER
                                value: 192.168.229.132
                             -  name: NFS_PATH
                                value: /nfs_data
                    volumes:
                       - name: nfs-client-root
                         nfs:
                           server: 192.168.229.132
                           path: /nfs_data
          - apiVersion: storage.k8s.io/v1
            kind: StorageClass
            metadata:
              name: nfs-sc
            provisioner: fuseim.pri/ifs
            reclaimPolicy: Retain
          - apiVersion: v1
            kind: PersistentVolumeClaim
            metadata:
              name: test-claim
            spec:
              storageClassName: nfs-sc
              accessModes:
                - ReadWriteMany
              resources:
                requests:
                  storage: 10Mi
```

```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: task
spec:
  components:
    - name: job
      type: task
      properties:
        image: busybox
        cmd: ["echo","Hello World"]
        volumes:
        - name: test
          mountPath: /var/test
          type: configMap
          defaultMode: 400
          cmName: myconfig
          items:
          - key: username
            mode: 400
            path: myname
    - name: myconfig
      type: k8s-objects
      properties:
        objects:
          - apiVersion: v1
            data:
              username: test
            kind: ConfigMap
            metadata:
              name: myconfig
```

```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: task
spec:
  components:
    - name: job
      type: task
      properties:
        image: busybox
        cmd: ["echo","Hello World"]
        volumes:
        - name: test
          mountPath: /var/test
          type: secret
          defaultMode: 444
          secretName: mysecret
          items:
          - key: username
            mode: 400
            path: myname
    - name: mysecret
      type: k8s-objects
      properties:
        objects:
          - apiVersion: v1
            kind: Secret
            metadata:
              name: mysecret
            type: Opaque
            data:
              username: YWRtaW4=
              password: MWYyZDFlMmU2N2Rm
```

vela status task

![lQLPJxbTch4B8oDNAbbNAk2wwG2BtXLQ9PgDW3_B_EDsAA_589_438 png_620x10000q90](https://user-images.githubusercontent.com/31508490/198865358-b0ca1b10-75d8-44f8-b30f-e38ba004c006.jpg)

![c35fffb38f3d1af82a7d7a2a9626209c7117c5dd042ad7f056e6c0711b38b8a4QzpcVXNlcnNcMTk1NDRcQXBwRGF0YVxSb2FtaW5nXERpbmdUYWxrXDI3OTkyODAzOF92MlxJbWFnZUZpbGVzXDE2NjcxMTA3NTQyNTZfQzIyRkNBQjktQzI3Mi00OGFhLUEyRDEtOUQzRTU1OEU1RUE4LnBuZw==](https://user-images.githubusercontent.com/31508490/198865409-136f8111-650d-43d0-afe8-c3823256d68e.png)

**Expected behavior**

type correct

**Screenshots**

**KubeVela Version**
v1.5.8

**Cluster information**

v1.21.0
**Additional context**

**Comment by chivalryq** [comment] 2022-11-02 09:46
I can't re-produce this bug. Can you follow this steps to give more information?

1. Apply application which will cause the problem.
2. Run `vela status` and confirm the type isn't right.
3. **Run `kubectl get app <you-app> -o yaml` and paste the YAML printed**

**Comment by 13567436138** [comment] 2022-11-06 09:18
yaml change suggestion
···
          - kind: ClusterRoleBinding
            apiVersion: rbac.authorization.k8s.io/v1
            metadata:
              name: run-nfs-provisioner
            subjects:
              - kind: ServiceAccount
                name: nfs-provisioner
                namespace: prod
            roleRef:
              kind: ClusterRole
              name: nfs-provisioner-runner
              apiGroup: rbac.authorization.k8s.io
···
change the namespace: prod if your app is not install in the namespace prod

```
          - kind: Deployment
            apiVersion: apps/v1
            metadata:
               name: nfs-client-provisioner
            spec:
               selector:
                 matchLabels:
                   app: nfs-client-provisioner
               replicas: 1
               strategy:
                 type: Recreate
               template:
                  metadata:
                    labels:
                      app: nfs-client-provisioner
                  spec:
                    serviceAccount: nfs-provisioner
                    containers:
                        -  name: nfs-client-provisioner
                           image: quay.io/external_storage/nfs-client-provisioner:latest
                           volumeMounts:
                             -  name: nfs-client-root
                                mountPath:  /persistentvolumes
                           env:
                             -  name: PROVISIONER_NAME
                                value: fuseim.pri/ifs
                             -  name: NFS_SERVER
                                value: 192.168.229.132
                             -  name: NFS_PATH
                                value: /nfs_data
                    volumes:
                       - name: nfs-client-root
                         nfs:
                           server: 192.168.229.132
                           path: /nfs_data
```
changed the flowing settings,according your config:
                             -  name: NFS_SERVER
                                value: 192.168.229.132
                             -  name: NFS_PATH
                                value: /nfs_data
                    volumes:
                       - name: nfs-client-root
                         nfs:
                           server: 192.168.229.132
                           path: /nfs_data

**Comment by 13567436138** [comment] 2022-11-06 09:25
```
^C[root@node01 task]# kubectl get app -n prod task -o yaml
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"core.oam.dev/v1beta1","kind":"Application","metadata":{"annotations":{},"name":"task","namespace":"prod"},"spec":{"components":[{"name":"job","properties":{"cmd":["echo","Hello World"],"image":"busybox","volumes":[{"defaultMode":444,"items":[{"key":"username","mode":400,"path":"myname"}],"mountPath":"/var/test","name":"test","secretName":"mysecret","type":"secret"}]},"type":"task"},{"name":"mysecret","properties":{"objects":[{"apiVersion":"v1","data":{"password":"MWYyZDFlMmU2N2Rm","username":"YWRtaW4="},"kind":"Secret","metadata":{"name":"mysecret"},"type":"Opaque"}]},"type":"k8s-objects"}]}}
    oam.dev/kubevela-version: v1.5.8
  creationTimestamp: "2022-11-06T08:20:34Z"
  finalizers:
  - app.oam.dev/resource-tracker-finalizer
  generation: 3
  name: task
  namespace: prod
  resourceVersion: "2063246"
  selfLink: /apis/core.oam.dev/v1beta1/namespaces/prod/applications/task
  uid: 30870642-58a1-4c24-814b-7d0d142774b6
spec:
  components:
  - name: job
    properties:
      cmd:
      - echo
      - Hello World
      image: busybox
      volumes:
      - defaultMode: 444
        items:
        - key: username
          mode: 400
          path: myname
        mountPath: /var/test
        name: test
        secretName: mysecret
        type: secret
    type: task
  - name: mysecret
    properties:
      objects:
      - apiVersion: v1
        data:
          password: MWYyZDFlMmU2N2Rm
          username: YWRtaW4=
        kind: Secret
        metadata:
          name: mysecret
        type: Opaque
    type: k8s-objects
status:
  appliedResources:
  - apiVersion: batch/v1
    creator: workflow
    kind: Job
    name: job-task-v3
    namespace: prod
  - apiVersion: v1
    creator: workflow
    kind: Secret
    name: mysecret
    namespace: prod
  conditions:
  - lastTransitionTime: "2022-11-06T08:20:34Z"
    reason: Available
    status: "True"
    type: Parsed
  - lastTransitionTime: "2022-11-06T08:20:34Z"
    reason: Available
    status: "True"
    type: Revision
  - lastTransitionTime: "2022-11-06T08:20:34Z"
    reason: Available
    status: "True"
    type: Policy
  - lastTransitionTime: "2022-11-06T08:20:34Z"
    reason: Available
    status: "True"
    type: Render
  - lastTransitionTime: "2022-11-06T08:22:29Z"
    reason: Available
    status: "True"
    type: Workflow
  - lastTransitionTime: "2022-11-06T08:22:45Z"
    message: 'Waiting for PersistentVolumeClaim test-claim (Namespace: prod) to delete.
      (At least 1 resources are deleting.)'
    reason: Deleting
    status: "False"
    type: Ready
  latestRevision:
    name: task-v3
    revision: 3
    revisionHash: c92d0f6e97adf5a1
  observedGeneration: 3
  services:
  - healthy: true
    message: Active/Failed/Succeeded:0/0/1
    name: job
    namespace: prod
    workloadDefinition:
      apiVersion: batch/v1
      kind: Job
  - healthy: true
    name: mysecret
    namespace: prod
    workloadDefinition:
      apiVersion: ""
      kind: ""
  status: running
  workflow:
    appRevision: task-v3:336d17d1951de965
    contextBackend:
      apiVersion: v1
      kind: ConfigMap
      name: workflow-task-context
      uid: 4453a5ae-8dc6-484c-b780-3748906166ac
    finished: true
    message: Succeeded
    mode: DAG
    startTime: "2022-11-06T08:22:02Z"
    steps:
    - firstExecuteTime: "2022-11-06T08:22:02Z"
      id: 7s6ppm64of
      lastExecuteTime: "2022-11-06T08:22:29Z"
      name: job
      phase: succeeded
      type: apply-component
    - firstExecuteTime: "2022-11-06T08:22:02Z"
      id: 7x8guq8wo2
      lastExecuteTime: "2022-11-06T08:22:02Z"
      name: mysecret
      phase: succeeded
      type: apply-component
    suspend: false
    terminated: false
```

```
[root@node01 task]# vela status task
About:

  Name:         task                         
  Namespace:    prod                         
  Created at:   2022-11-06 16:20:34 +0800 CST
  Status:       running                      

Workflow:

  mode: DAG
  finished: true
  Suspend: false
  Terminated: false
  Steps
  - id: 7s6ppm64of
    name: job
    type: apply-component
    phase: succeeded 
    message: 
  - id: 7x8guq8wo2
    name: mysecret
    type: apply-component
    phase: succeeded 
    message: 

Services:

  - Name: job  
    Cluster: local  Namespace: prod
    Type: task
    Healthy Active/Failed/Succeeded:0/0/1
    No trait applied

  - Name: mysecret  
    Cluster: local  Namespace: prod
    Type: k8s-objects
    Healthy 
    No trait applied
```

it seams it is ok now??????

**Comment by chivalryq** [comment] 2022-11-06 09:52
Yes, seems it works as expected. After I checked the code here, I think the problem of showing a completely different type of component is impossible. 
The possible situation is you applied a app with `webservice` first and run `vela ls` then you applied app without `webservice`.

I'm gonna closing this issue since it's not reproducible. Thanks for reporting.

**Closed by chivalryq** 2022-11-06 09:52 UTC
Labels: type/bug, needs more info
