### ISSUE TITLE
[Bug] `vela env init env-application` return an error

### ISSUE THREAD

**Issue by fourierr** [kubevela/kubevela#3947] opened 2022-05-22 07:44 UTC
**Describe the bug**

![1e171e819b670f18c9a27802268848d](https://user-images.githubusercontent.com/35767528/169684393-dd71d99a-13cc-455c-a46e-588fc2f9738b.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**KubeVela Version**
vela cli 1.3.3
vela core 1.3.3

**Cluster information**

Kubernetes Version 1.20
**Additional context**

The error message is not clear, and confuses me

**Comment by StevenLeiZhang** [comment] 2022-05-23 02:53
the default namespace is already  assigned to env "default". You can not override it.

**Comment by wonderflow** [comment] 2022-05-23 02:54
Yes, this is not a bug, but we need refine the output.

**Comment by fourierr** [comment] 2022-05-26 13:23
I will refine the the output for more clear.

**Closed** 2022-05-27 09:34 UTC
Labels: needs more info, area/cli
