### ISSUE TITLE
The quick start does not work for kind node version 1.21.1

### ISSUE THREAD

**Issue by dongwangdw** [kubevela/kubevela#1927] opened 2021-07-16 07:39 UTC
I followed the quick start from here https://kubevela.io/docs/install, with kind version 0.11.0, kind node version 1.21.1.

And I followed the book to deploy vela-app.yaml.
Then the app keeps pending:
```
NAME             COMPONENT        TYPE         PHASE            HEALTHY   STATUS   AGE
first-vela-app   express-server   webservice   healthChecking                      4h5m
```

I get error log from kubevela-vela-core:
```
"Failed to aggregate status" err=app=first-vela-app, comp=express-server, trait=ingress, check health error: get template context: failed to get obj express-server with gvk networking.k8s.io/v1beta1, Kind=Ingress : ingresses.networking.k8s.io "express-server" not found
```
I get the log from nginx controller:
```
"failed to process webhook request" err="rejecting admission review because the request does not contain an Ingress resource but networking.k8s.io/v1, Kind=Ingress with name express-server in namespace default"
```

Did I miss anyting? Please help.

**Comment by wonderflow** [comment] 2021-07-16 09:24
What is your K8s version, is it v1.21?

I think it's because the ingress API is changed. 

You can apply this ingress trait https://raw.githubusercontent.com/oam-dev/kubevela/master/charts/vela-core/templates/defwithtemplate/ingress-1-20.yaml

It's name is `ingress-1-20` to distinguish with `ingress`. And you can change the application like this:

```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: first-vela-app
spec:
  components:
    - name: express-server
      type: webservice
      properties:
        image: crccheck/hello-world
        port: 8000
      traits:
        - type: ingress-1-20
          properties:
            domain: testsvc.example.com
            http:
              "/": 8000
```

**Comment by dongwangdw** [comment] 2021-07-19 06:57
@wonderflow 
Thanks for the info. But it does not work either. The error is as below:
>TraitDefinition.core.oam.dev "ingress-1-20" not found

Maybe the ingress API should be upgraded.

**Comment by wonderflow** [comment] 2021-07-19 07:07
@dongwangdw Have you ever apply the yaml:

```
kubectl apply -f https://raw.githubusercontent.com/oam-dev/kubevela/master/charts/vela-core/templates/defwithtemplate/ingress-1-20.yaml
```

**Comment by dongwangdw** [comment] 2021-07-20 03:10
@wonderflow 
I deployed this traitDefinition to vela-system namespace.
Then I deployed the example app. But I got the same error.
Did I miss anything?

```
NAME           APPLIES-TO             DESCRIPTION
ingress-1-20   ["deployments.apps"]   Enable public web traffic for the component, the ingress API matches K8s v1.20+.

kg ingress -A
No resources found

NAME             COMPONENT        TYPE         PHASE            HEALTHY   STATUS   AGE
first-vela-app   express-server   webservice   healthChecking                      2m55s

```

The app pends on ```HealthChecking``` status.
Description of the APP.
>Application  app=first-vela-app, comp=express-server, trait=ingress-1-20, check health error: get template context: failed to get obj express-server with gvk networking.k8s.io/v1, Kind=Ingress : ingresses.networking.k8s.io "express-server" not found

**Comment by wonderflow** [comment] 2021-07-20 05:26
What's your k8s cluster version?

**Comment by dongwangdw** [comment] 2021-07-20 07:43
My cluster is Kind cluster 1.21.1.
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-13T02:40:46Z", GoVersion:"go1.16.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-18T01:10:20Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by dongwangdw** [comment] 2021-07-22 02:25
I cofirmed that the quick start can not work in kind1.21.1. But work well for 1.18.15.

https://github.com/oam-dev/kubevela/issues/1927#issuecomment-883017020
If there is no miss from my this comment. This will be a bug.

**Comment by wonderflow** [comment] 2021-07-22 02:32
We're investigating it, thanks for reporting

**Comment by wangyuan249** [comment] 2021-07-28 16:53
@dongwangdw  Hi~,  I follow your way to reproduce the problem. The conclusions I have so far are as follows:
1. The ingress-nginx controller provided by official which support Kubernetes >= v1.19 still have some problems.
In kind pre-release version ![v1.0.0 Alpha 2](https://github.com/kubernetes/ingress-nginx/blob/controller-v1.0.0-alpha.2/deploy/static/provider/kind/deploy.yaml).
![image](https://user-images.githubusercontent.com/35907099/127359293-0b30d9fa-8759-4523-aa71-6fd133c3c688.png). 

Therefore, the problem is not caused by kubevela, we should wait for the further official maintenance and repair. 

There are two ways to solve it. 
a.  in kind way : skip the check for webhook. 
1) install the ingress-nginx controller in any release version.
```shell
k apply -f  https://raw.githubusercontent.com/kubernetes/ingress-nginx/v1.0.0-alpha.1/deploy/static/provider/kind/deploy.yaml
```
mentioned that, if you find the deployment for ingress-nginx controller cannot run or pending.
![image](https://user-images.githubusercontent.com/35907099/127362026-4d2fd9c2-2ffd-4939-9355-997f1fbbfe5a.png)

you can edit the deployment yaml and delete the line `ingress-ready: "true"`  in `nodeSelector:` and restart.
![image](https://user-images.githubusercontent.com/35907099/127362176-e9086955-62db-424d-9bf9-4a833f8df892.png)

2) delete the validatingwebhookconfigurations and skip the check for webhook.
```shell
使用下面的命令查看 webhook
kubectl get validatingwebhookconfigurations
ingress-nginx-admission

删除ingress-nginx-admission
kubectl delete -A ValidatingWebhookConfiguration ingress-nginx-admission

```
related info are provided in here ![issue1](https://github.com/kubernetes/ingress-nginx/issues/7305), ![issue2](https://github.com/kubernetes-sigs/kind/pull/2306), ![webpage1](https://blog.csdn.net/qq_39218530/article/details/115372879)

3) Run `make check-install-def` in KubeVela root path and apply the app use ingress-1-20. Then you can see the app is running.

b.  in minikube way.  
The porblem that ingress-nginx controller could not support Kubernetes >= v1.19 is fixed in minikube environment.
And you can install the ingress-nginx for latest version. 
If you find the deployment for ingress-nginx controller cannot run or pending, fix it as the way above.
then, you can apply your application and run normally in KubeVela system.

**Closed** 2023-07-06 08:53 UTC
Labels: needs investigation
