### ISSUE TITLE
Page not found at the url: https://kubevela.io/docs/contributor/overview/code-contribute 

### ISSUE THREAD

**Issue by punithnayak** [kubevela/kubevela#6227] opened 2023-07-23 18:45 UTC
**Describe the bug**

Error 404 page displayed when request is made to https://kubevela.io/docs/contributor/overview/code-contribute

**To Reproduce**

Go to https://kubevela.io/docs/contributor/overview/code-contribute

**Expected behavior**

There should be content When made hit to that particular URL

**Screenshots**

![image](https://github.com/kubevela/kubevela/assets/110713318/4c5fb93f-5c6a-4a64-a2e7-5e50d145a31c)

**Comment by wonderflow** [comment] 2023-07-24 01:40
Try this link: https://kubevela.io/docs/contributor/code-contribute

**Comment by chivalryq** [comment] 2023-07-25 02:27
Which button leads to this page? If there isn't any it's not a issue.

**Comment by punithnayak** [comment] 2023-07-25 11:24
This happens only in Mozila firefox not on chrme

**Comment by chivalryq** [comment] 2023-07-26 03:10
Not sure if this problem is caused by docusorus which is the document framework we use.

**Comment by AndrewScheller2006** [comment] 2023-09-08 01:03
.

**Comment by chivalryq** [comment] 2023-09-08 09:29
Fixed in https://github.com/kubevela/kubevela.github.io/pull/1269.

Now all the link should go with the trailing slash. In this case, the URL is: https://kubevela.io/docs/contributor/code-contribute/

**Closed by chivalryq** 2023-09-08 09:29 UTC
