### ISSUE TITLE
apply application.yaml后部署延迟严重

### ISSUE THREAD

**Issue by zengqinglie** [kubevela/kubevela#4015] opened 2022-05-27 02:46 UTC
**Describe the bug**

提交application.yaml成功后，到application部署成功，延迟超过5分钟。
**To Reproduce**

1. Components&traits: 
comp: cy-deploy(与webservice类似)
trait: scaler
policy: env-binding-policy

2. application yaml:
```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: demo-nginx
  namespace: vela-system-tools-prod-platform-master
spec:
  components:
  - name: demo-nginx-cy-deploy
    properties:
      adEnv:
      - name: AD_ENV_CODE
        value: prod
      appcode: demo-nginx
      cpuLimits: "1"
      cpuRequests: "0.1"
      image: nginx
      memoryLimits: 1Gi
      memoryRequests: 100Mi
      port: 8080
    traits:
    - properties: {}
      type: scaler
    type: cy-deploy
  policies:
  - name: env-binding-policy
    properties:
      envs:
      - name: prod
        patch:
          components:
          - name: demo-nginx-cy-deploy
            properties:
              cpuLimits: "2"
            traits:
            - properties:
                replicas: 2
              type: scaler
            type: cy-deploy
        placement:
          clusterSelector:
            name: yunzhen-hz-dmz-k8s
          namespaceSelector:
            name: tools-prod-platform-master
    type: env-binding
  workflow:
    steps:
    - name: demo-nginx-deploy2env
      properties:
        env: prod
        policy: env-binding-policy
      type: deploy2env
```

**Expected behavior**

立即部署demo-nginx application, 生成deployment&pod
**Screenshots**

无

**KubeVela Version**

**版本:** 
CLI Version: v1.3.2
Core Version: 1.3.2
GitRevision: git-d08aa7d
GolangVersion: go1.17.8

**vela-core info:**
```
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: kubevela
      app.kubernetes.io/name: vela-core
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: kubevela
        app.kubernetes.io/name: vela-core
    spec:
      containers:
      - args:
        - --metrics-addr=:8080
        - --enable-leader-election
        - --use-webhook=true
        - --webhook-port=9443
        - --webhook-cert-dir=/etc/k8s-webhook-certs
        - --health-addr=:9440
        - --disable-caps=rollout
        - --system-definition-namespace=vela-system
        - --application-revision-limit=10
        - --definition-revision-limit=10
        - --oam-spec-ver=v0.3
        - --enable-cluster-gateway
        - --application-re-sync-period=1440m
        - --concurrent-reconciles=100
        - --kube-api-qps=1000
        - --kube-api-burst=2000
        - --max-workflow-wait-backoff-time=60
        - --max-workflow-failed-backoff-time=300
        - --max-workflow-step-error-retry-times=1
        image: oamdev/vela-core:v1.3.2
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: healthz
            scheme: HTTP
          initialDelaySeconds: 90
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        name: kubevela
        ports:
        - containerPort: 9443
          name: webhook-server
          protocol: TCP
        - containerPort: 9440
          name: healthz
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /readyz
            port: healthz
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: "4"
            memory: 2Gi
          requests:
            cpu: 50m
            memory: 20Mi
        securityContext: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/k8s-webhook-certs
          name: tls-cert-vol
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: kubevela-vela-core
      serviceAccountName: kubevela-vela-core
      terminationGracePeriodSeconds: 30
      volumes:
      - name: tls-cert-vol
        secret:
          defaultMode: 420
          secretName: kubevela-vela-core-admission
```

**kubevela-cluster-gateway info:**
```
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: kubevela-cluster-gateway
      app.kubernetes.io/name: vela-core-cluster-gateway
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: kubevela-cluster-gateway
        app.kubernetes.io/name: vela-core-cluster-gateway
    spec:
      containers:
      - args:
        - apiserver
        - --secure-port=9443
        - --secret-namespace=vela-system
        - --feature-gates=APIPriorityAndFairness=false
        - --cert-dir=/etc/k8s-cluster-gateway-certs
        image: oamdev/cluster-gateway:v1.3.2
        imagePullPolicy: IfNotPresent
        name: kubevela-vela-core-cluster-gateway
        ports:
        - containerPort: 9443
          protocol: TCP
        resources:
          limits:
            cpu: "2"
            memory: 1000Mi
        securityContext: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/k8s-cluster-gateway-certs
          name: tls-cert-vol
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: kubevela-vela-core
      serviceAccountName: kubevela-vela-core
      terminationGracePeriodSeconds: 30
      volumes:
      - name: tls-cert-vol
        secret:
          defaultMode: 420
          secretName: kubevela-vela-core-cluster-gateway-tls
```

**Cluster information**

Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.16", GitCommit:"e37e4ab4cc8dcda84f1344dda47a97bb1927d074", GitTreeState:"clean", BuildDate:"2021-10-27T16:25:59Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.16", GitCommit:"e37e4ab4cc8dcda84f1344dda47a97bb1927d074", GitTreeState:"clean", BuildDate:"2021-10-27T16:20:18Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}

**Additional context**

vela-core启动时有大量patching object
```
I0527 02:35:58.636201       1 apply.go:107] "patching object" name="ufs" resource="/v1, Kind=ServiceAccount"
I0527 02:35:58.835259       1 apply.go:107] "patching object" name="bss-nexus" resource="/v1, Kind=ServiceAccount"
I0527 02:35:59.035642       1 apply.go:107] "patching object" name="gateway-sz" resource="/v1, Kind=ServiceAccount"
I0527 02:35:59.236291       1 apply.go:107] "patching object" name="guide-cfg-page" resource="/v1, Kind=ServiceAccount"
I0527 02:35:59.435007       1 apply.go:107] "patching object" name="vii-tyg" resource="/v1, Kind=ServiceAccount"
```
且耗时都相当久, 以下为某一个spanID的日志:
```
I0527 02:33:34.073900       1 application_controller.go:110] "Start reconcile application" application="vela-system-biz-pre-vii-master/bss-crm" controller="application" spanID="i-q51lcos3"
I0527 02:33:34.074027       1 apply.go:74] "[Finished]: i-q51lcos3.create-app-handler(finish create appHandler)" application="vela-system-biz-pre-vii-master/bss-crm" controller="application" resource_version="15101842" generation=8 publish_version="v1.3.2" duration="54.738µs" spanID="i-q51lcos3.create-app-handler"
I0527 02:33:34.074215       1 parser.go:102] "[Finished]: i-q51lcos3.generate-app-file(finish generate appFile)" application="vela-system-biz-pre-vii-master/bss-crm" controller="application" resource_version="15101842" generation=8 publish_version="v1.3.2" duration="162.391µs" spanID="i-q51lcos3.generate-app-file"
I0527 02:33:34.075062       1 revision.go:191] "[Finished]: i-q51lcos3.prepare-current-appRevision(finish prepare current appRevision)" application="vela-system-biz-pre-vii-master/bss-crm" controller="application" resource_version="15101842" generation=8 publish_version="v1.3.2" duration="809.363µs" spanID="i-q51lcos3.prepare-current-appRevision"
I0527 02:33:34.084656       1 revision.go:780] "[Finished]: i-q51lcos3.apply-app-revision(finish apply app revision)" application="vela-system-biz-pre-vii-master/bss-crm" controller="application" resource_version="15101842" generation=8 publish_version="v1.3.2" duration="9.562497ms" spanID="i-q51lcos3.apply-app-revision"
I0527 02:33:34.084682       1 application_controller.go:173] "Successfully prepare current app revision" application="vela-system-biz-pre-vii-master/bss-crm" controller="application" resource_version="15101842" generation=8 publish_version="v1.3.2" revisionName="bss-crm-v8" revisionHash="2b672fc8cfcdddc" isNewRevision=false spanID="i-q51lcos3"
I0527 02:33:34.084704       1 application_controller.go:182] "Successfully apply application revision" application="vela-system-biz-pre-vii-master/bss-crm" controller="application" resource_version="15101842" generation=8 publish_version="v1.3.2" spanID="i-q51lcos3"
I0527 02:33:34.084722       1 apply.go:345] "[Finished]: i-q51lcos3.apply-policies(finish apply policies)" application="vela-system-biz-pre-vii-master/bss-crm" controller="application" resource_version="15101842" generation=8 publish_version="v1.3.2" duration="1.892µs" spanID="i-q51lcos3.apply-policies"
I0527 02:33:34.085138       1 application_controller.go:247] "Workflow state=Finished" application="vela-system-biz-pre-vii-master/bss-crm" controller="application" resource_version="15101842" generation=8 publish_version="v1.3.2" spanID="i-q51lcos3"
I0527 02:36:17.035376       1 application_controller.go:270] "Successfully garbage collect" application="vela-system-biz-pre-vii-master/bss-crm" controller="application" resource_version="15101842" generation=8 publish_version="v1.3.2" spanID="i-q51lcos3"
I0527 02:36:17.039675       1 application_controller.go:314] "GarbageCollected resourcetrackers" application="vela-system-biz-pre-vii-master/bss-crm" controller="application" resource_version="15101842" generation=8 publish_version="v1.3.2" spanID="i-q51lcos3"
I0527 02:36:17.046584       1 application_controller.go:318] "[Finished]: i-q51lcos3.gc_resourceTrackers(finish gc resourceTrackers)" application="vela-system-biz-pre-vii-master/bss-crm" controller="application" resource_version="15101842" generation=8 publish_version="v1.3.2" duration="11.15904ms" spanID="i-q51lcos3.gc_resourceTrackers"
I0527 02:36:17.046610       1 application_controller.go:278] "[Finished]: i-q51lcos3(End reconcile application)" application="vela-system-biz-pre-vii-master/bss-crm" controller="application" resource_version="15101842" generation=8 publish_version="v1.3.2" duration="2m42.972715484s" spanID="i-q51lcos3"
```

在所有patching object全部执行完后，部署响应恢复正常

**Comment by captainroy-hy** [comment] 2022-05-27 03:04
https://github.com/kubevela/kubevela/blob/6bef810dc33e4c4fc61b740b6943c10dfc1784bf/pkg/utils/apply/apply.go#L169

**Comment by Somefive** [comment] 2022-05-27 12:17
Upgrading cluster-gateway to v1.4.0 generally solved this problem. It is largely caused by the rate limit of cluster-gateway. 
The patch enhancement is encouraged and let's make it for future.

**Comment by fourierr** [comment] 2022-05-28 09:16
Is there a specific time to upgrade cluster-gateway to v1.4.0?

**Comment by fourierr** [comment] 2022-05-28 09:16
> Upgrading cluster-gateway to v1.4.0 generally solved this problem. It is largely caused by the rate limit of cluster-gateway. The patch enhancement is encouraged and let's make it for future.

Is there a specific time to upgrade cluster-gateway to v1.4.0? @Somefive

**Comment by Somefive** [comment] 2022-05-30 02:27
> 

KubeVela v1.4.0-beta.2 uses cluster-gateway v1.4.0 by default. As far as I see, you can upgrade cluster-gateway to v1.4.0 at any KubeVela version you want.

**Comment by chivalryq** [comment] 2022-05-31 02:01
Closing.
@zengqinglie If the upgrading cluster-gateway didn't solve your problem, feel free to reopen this issue.

**Closed by chivalryq** 2022-05-31 02:01 UTC
Labels: type/enhancement, priority/important-soon, area/performance
