### ISSUE TITLE
Unable to enable CloudShell addon

### ISSUE THREAD

**Issue by h7kanna** [kubevela/kubevela#4400] opened 2022-07-18 03:48 UTC
**Describe the bug**

Unable to enable CloudShell addon

Error: https://release.daocloud.io/chartrepo/cloudshell/index.yaml": dial tcp 113.31.108.245:443:

**To Reproduce**

1. Enable VelaUX
2. Go to Platform Setting
3. Go to Enable CloudShell

**Expected behavior**
CloudShell addon enabled.

**Screenshots**
<img width="1767" alt="Screen Shot 2022-07-17 at 10 47 21 PM" src="https://user-images.githubusercontent.com/2949492/179442524-f3f6f73a-0b21-4eed-bfd3-f1d7a44b1f0e.png">

**KubeVela Version**

v1.5.0-alpha.3

**Cluster information**
Kubernetes Version 1.22.9

**Additional context**

**Comment by wangyikewxgm** [comment] 2022-07-18 03:54
The reason might be your network has some problems. Can you access the helmRepo?

**Comment by StevenLeiZhang** [comment] 2022-07-18 06:10
https://github.com/kubevela/catalog/blob/95182838e0685a8c06e5405d25cce3e5e43c735a/addons/cloudshell/template.yaml#L12

I think it is better to expose one input parameter, and let user set the Chart's URL.

**Comment by h7kanna** [comment] 2022-07-24 03:18
I am able to enable addon now, may be a network issue.
But it did occure repeatedly before.

**Comment by wonderflow** [comment] 2022-08-11 03:31
closing as it's not reproducable.

**Closed by wonderflow** 2022-08-11 03:31 UTC
Labels: needs investigation
